# Generated by Django 3.1 on 2021-02-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210204_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='blog',
            new_name='main_blog',
        ),
    ]
